# Generated by Django 5.1.1 on 2024-10-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact_Number', models.CharField(max_length=13, unique=True)),
                ('Address', models.CharField(max_length=100)),
                ('User_Id', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=256)),
                ('Government_Id', models.ImageField(upload_to='GovermentId/')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cluster_Name', models.CharField(max_length=100)),
                ('Delivery_Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.agent')),
                ('School', models.ManyToManyField(to='authapp.school')),
            ],
        ),
    ]
