# Generated by Django 5.1.1 on 2024-10-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_agent_deliverycluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycluster',
            name='School',
            field=models.ManyToManyField(blank=True, null=True, to='authapp.school'),
        ),
    ]
