# Generated by Django 5.1.1 on 2024-10-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_deliverycluster_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycluster',
            old_name='School',
            new_name='school',
        ),
    ]
