# Generated by Django 5.1.1 on 2024-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Plan_Type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly')], max_length=10),
        ),
    ]
