# Generated by Django 5.1.1 on 2024-10-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_school_deliverycluster_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycluster',
            name='school',
            field=models.ManyToManyField(to='authapp.school'),
        ),
    ]
