# Generated by Django 5.1.1 on 2024-10-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Item_Quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
