# Generated by Django 5.1.1 on 2024-10-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_subscription_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='payment_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
