# Generated by Django 5.1.1 on 2024-10-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_alter_transactiondetail_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_status',
        ),
    ]
