# Generated by Django 5.1.1 on 2024-10-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_remove_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='Payment_id',
            new_name='Payment_order_id',
        ),
    ]
