# Generated by Django 5.1.1 on 2024-10-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_rename_payment_id_transactiondetail_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='child',
        ),
    ]
